### ISSUE TITLE
Issue accessing OSquery.io/schema via direct link

### ISSUE THREAD

**Issue by Pelios** [osquery/osquery-site#137]
Currently when I try and access the OSquery.io/Schema webpage on desktop, either via the direct link or navigating through the OSquery.io page, the page does not load and only a blank page is displayed. 

When accessed on mobile I am able to successfully load the page via navigating to it via the OSquery.io website. If I request the desktop page while on the successfully loaded schema page a 404 error will be displayed. Also the same 404 error is displayed if i attempt to follow the direct link to the page.

**Comment by directionless** [comment]
I beleive this issue occurs when you visit the schema page directly in a fresh browser.

Reproduce:
1. Launch fresh/private window (firefox seems better than chrome)
2. visit https://osquery.io/schema/3.3.2
3. Observe 404
4. Visit https://osquery.io and click schema
5. URL looks the same

**Comment by theopolis** [comment]
This is indeed an issue. This might be the solution: https://github.com/facebook/create-react-app/issues/1765

**Comment by zwass** [comment]
Fixed in #138
