### ISSUE TITLE
Add windows packages to downloads page

### ISSUE THREAD

**Issue by marpaia** [osquery/osquery-site#18]
As of `2.11.2`, windows msi packages are available at https://pkg.osquery.io/windows/osquery-2.11.2.msi. Links and hashes for these packages should be added to the downloads page. @FritzX6 prepared this mock which stacks the download information in 5 cards when available (2x2x1):

![image 2](https://user-images.githubusercontent.com/927168/35357231-2888714c-0110-11e8-916f-73f9cf72c9ab.png)

Versions prior to 2.11.2 should stack the available 4 cards the same way it is now, 2x2.

**Comment by FritzX6** [comment]
👍

**Comment by theopolis** [comment]
:+1:

**Comment by marpaia** [comment]
<img width="1259" alt="screen shot 2018-01-29 at 9 43 24 am" src="https://user-images.githubusercontent.com/927168/35522187-e248a7f2-04d8-11e8-90ee-912a4e2e259b.png">
