### ISSUE TITLE
Website references FreeBSD when platform is poorly supported

### ISSUE THREAD

**Issue by FritzX6** [osquery/osquery-site#185]
### What is the problem?
There are many places across the osquery website that reference FreeBSD support (including table compatibility in the schema). It is my understanding that osquery does not currently support FreeBSD and this leads to confusion from individuals who attempt to use osquery on that platform.

### Proposed solution
Until FreeBSD support is fixed, we should temporarily remove references to the platform so as not to mislead prospective osquery users.

**Comment by directionless** [comment]
This got purged out recently
