### ISSUE TITLE
Restore the dropper icon for tables schema, with required columns

### ISSUE THREAD

**Issue by mike-myers-tob** [osquery/osquery-site#189]
[The documentation for “Tables with arguments"](https://osquery.readthedocs.io/en/stable/introduction/sql/#tables-with-arguments) says “These tables, and their columns, are flagged by a dropper icon in the schema documentation as requiring a column or as using a column to generate additional information.”   However, this dropper icon is not present in the schema section of the current website.

I think this is referring to tables that have one or more columns that are `required=True`. Should this be an indication on the table, then, or an indication on the column? I would favor it being marked in the column description.

I failed to find a time when a dropper icon might have appeared. There doesn't appear to have been one in https://github.com/osquery/osquery-site/tree/source/src/components/Icon/svg

**Comment by FritzX6** [comment]
@mike-myers-tob this was part of the old schema page:
![image](https://user-images.githubusercontent.com/931724/97066134-e5c7b600-1580-11eb-93de-c8964a95147b.png)

This was planned for inclusion in the initial osquery.io redesign and never got finished. The proposed mocks are here:
![image](https://user-images.githubusercontent.com/931724/97066181-54a50f00-1581-11eb-9b2c-0392434fc262.png)


Of note there were several other icons intended to convey additional information about specific columns:
![image](https://user-images.githubusercontent.com/931724/97066202-861dda80-1581-11eb-8301-4c403ea4cd01.png)

**Comment by zhumo** [comment]
@mike-myers-tob @FritzX6 do you have those icons or assets somewhere? I'd love to take a stab at getting this information included in the schema. This stuff is important and non-obvious for users! If there's pre-existing work, that'd be really helpful.

**Comment by directionless** [comment]
@FritzX6 Are those your mocks, and do you have those icons?

Digging around a bunch, I see old versions of this at https://web.archive.org/web/20170809185932/https://osquery.io/docs/tables/ 

But I do not see that in the code base here, which seem to all post-date a site rewrite.

**Comment by zhumo** [comment]
If I may suggest, I think there is opportunity to have a few other icons:
1. user-context dependent
2. M1/Arm/etc. vs. Intel

I got tripped up by these when learning osquery, esp. (1). I know (2) is an ongoing problem.
