### ISSUE TITLE
Update schema page to document event-based tables and tables that require a query predicate

### ISSUE THREAD

**Issue by marpaia** [osquery/osquery-site#21]
Some osquery tables are populated via osquery's evented pubsub system which allows the administrator to monitor real-time events using a typical poll user-experience. Additionally, some tables *require* a query predicate to run (ie: you must specify `path` when you query the `hash` table). We should reason about how to best educate users about this and push an update to the schema page.

**Comment by taylorkearns** [comment]
@marpaia for evented tables, should we go with this? I must have just missed this in the original build. This is the `evented` flag in the data, correct?

<img width="843" alt="screenshot 2018-05-29 15 40 19" src="https://user-images.githubusercontent.com/311215/40681275-b248bfd8-6356-11e8-8c0d-983b9708e2c5.png">

**Comment by marpaia** [comment]
Yup @taylorkearns, the "evented" key on each table indicates whether or not the table is event-based and the "required" key of each column indicates whether or not the column is required.

**Comment by taylorkearns** [comment]
@FritzX6 do you have thoughts on treatment for a required column? An asterisk?

**Comment by taylorkearns** [comment]
Evented tables addressed by #74
