### ISSUE TITLE
Add Windows platform support to Yara tables

### ISSUE THREAD

**Issue by mike-myers-tob** [osquery/osquery-site#212]
https://github.com/osquery/osquery-site/blob/e2cef28493566abdfde2cc464d27044d3b935bfc/src/data/osquery_schema_versions/4.7.0.json#L22244

The `yara` table should show Windows support on the osquery schema page. Support was added last July in this PR: https://github.com/osquery/osquery/pull/6564

I'm not sure where this ought to be indicated, since I assume this json file is auto-generated by @theopolis somehow.

https://github.com/osquery/osquery/blob/master/specs/CMakeLists.txt#L306

**Comment by directionless** [comment]
The website has a lot of gnarly codegen. It starts with https://github.com/osquery/osquery-site/blob/source/tools/new_release.sh and quickly moves to python scripts in the osquery repo. TBH the whole thing could use a deep overhaul. But then again. so could the website.
