### ISSUE TITLE
Add CI to the PR process

### ISSUE THREAD

**Issue by marpaia** [osquery/osquery-site#27]
Right now, we have `yarn lint` as an available lint command, we should start running it via CI to make sure that we don't regress on lint issues.

**Comment by nhpace** [comment]
Need to understand the cloudbuild setup better...

**Comment by mike-myers-tob** [comment]
@directionless was this closed by https://github.com/osquery/osquery-site/pull/219 ? It looks like CI is run on PRs: https://github.com/osquery/osquery-site/blob/source/.github/workflows/ci.yml#L10

**Comment by directionless** [comment]
It's not perfect, but I think it's good enough and this ticket doesn't need to be here.
