### ISSUE TITLE
List Windows on Arm version

### ISSUE THREAD

**Issue by pbo-linaro** [osquery/osquery-site#284]
With osquery 5.9.1, windows on arm binaries are now available.

Can it be added to the osquery website?
Is the package already available on https://pkg.osquery.io/windows/? (what's the URL?)

Thanks

**Comment by directionless** [comment]
Looking at this...

The website downloads are generated by https://github.com/osquery/osquery-site/blob/source/tools/new_release.rb (which makes lots of assumptions about where the build pipeline puts things)

_But_ the website also only offers the MSI downloads, and IIRC the arm port does not yet have an MSI, just the exe. I am unsure if we should add executables there (vs leaving them in github) or what.

**Comment by pbo-linaro** [comment]
Indeed, I looked at this file, but my question was more to know how msi are being pushed to https://pkg.osquery.io?

**Comment by directionless** [comment]
I don't think we copy zip files to `pkg` today, we assume people will find them on the GitHub release page. 

It would be easy to add that to the build scripts in https://github.com/osquery/osquery-codesign (not public), but without updating the website that seems like it would be low value.

Maybe we should add the zip files to the `Alternative Install Options` install section?

**Comment by pbo-linaro** [comment]
Any link or mention on the website would work. You're right, people interested can always find it on GitHub as well.

**Comment by directionless** [comment]
@pbo-linaro I've added it to the "alternative install options" section. It doesn't feel ideal, but I'm not sure how to improve without a larger redesign effort. Happy for suggestions

**Comment by pbo-linaro** [comment]
It's a great solution. One suggestion though, it would be nice to make the release link clickable:
... build on the [GitHub releases](https://github.com/osquery/osquery/releases) page.

But the page available is already good :+1: .
Thanks for adding it!

**Comment by directionless** [comment]
I am embarrassed to admit that I tried to make it clickable, but couldn't unravel enough react to do that. I don't have a lot of js experience. You're welcome to try.

**Comment by pbo-linaro** [comment]
This [PR](https://github.com/osquery/osquery-site/pull/287) should do it.
I'm not an expert, but it seems like the string "paragraph" is used directly for the page, so raw html should work.
