### ISSUE TITLE
OS Icons on the schema page appear to be inaccurate sometimes

### ISSUE THREAD

**Issue by clong** [osquery/osquery-site#29]
windows_crashes shows icons for all OS'es:
![image](https://user-images.githubusercontent.com/5092699/35417069-9c7d3d6e-01e0-11e8-8a81-e808111341e1.png)

xprotect_entries shows icons for all OS'es:
![image](https://user-images.githubusercontent.com/5092699/35417087-b352c8b0-01e0-11e8-937a-81210d7fc977.png)

**Comment by monkykap** [comment]
i've noticed this for some other tables as well.

![image](https://user-images.githubusercontent.com/4961844/35466077-9d7930a8-02b5-11e8-9747-66d8717912f2.png)

![image](https://user-images.githubusercontent.com/4961844/35466092-bcf90818-02b5-11e8-8ad8-eafbec2bc9dc.png)

![image](https://user-images.githubusercontent.com/4961844/35466110-e80af3a4-02b5-11e8-891d-d2dcac5ffa70.png)

routes, interface_addresses, interface_details all work for windows. the windows section look's a little light in general, i think there are probably a few more tables. i'll post here as i come across them.

**Comment by mike-myers-tob** [comment]
This is also true for the `groups` table, where Windows is supported but the icon is missing in the schema page. For what it's worth, the `groups` table has an extended schema with Windows-only column, and the schema page depicts them inline with the other columns. That may confuse users of other platforms who would not see those columns in their `groups` table.

**Comment by terracatta** [comment]
Per @groob 

> I see that `os_version` is supported on windows but the website says otherwise https://github.com/facebook/osquery/blob/d058e19345acc24b69517a2e5fcd60a19dad78da/osquery/tables/system/windows/os_version.cpp

> none of the top level specs show up under windows support https://github.com/facebook/osquery/tree/master/specs

It's likely @marpaia needs to fix the data import script to take this top-level into account.

**Comment by muffins** [comment]
Any updates here? This is causing lots of confusion for folks leveraging the agent.

**Comment by marpaia** [comment]
The problem here is that `PLATFORM_DIRS` variable in the `tools/codegen/genwebsitejson.py` contains an incorrect mapping. From that script:

```
# In the specs/ directory of the osquery repository, specification files are put
# in certain directories based on what platforms they are meant to be built on.
# This data structure represents the directories in specs/ and how they map to
# the operating systems which support tables found in those directories
PLATFORM_DIRS = {
```

@groob opened https://github.com/facebook/osquery/pull/4248 to update the script and I've opened https://github.com/osquery/osquery-site/pull/58 which updates the existing table JSON given the new `PLATFORM_DIRS` values.

**Comment by marpaia** [comment]
@groob came in with a React logic bugfix in #59 to get this over the finish line, but between #58 and #59, all of the icons look accurate. I'm going to close this, but if there are any more inaccurate icons, let's definitely re-open this.

I created #60 to track the bug that @mike-myers-tob brought up with the extended schemas not being displayed, we're going to have to update the script and the UI for that.
