### ISSUE TITLE
Osquery version 5.12.2 is missing from site

### ISSUE THREAD

**Issue by lszcs90** [osquery/osquery-site#298]
Hello, 

Osquery released https://github.com/osquery/osquery/releases/tag/5.12.2 as hotfix. This is the latest release on github. 

This version is missing from the site: 
* json schema section: osquery-site/tree/source/src/data/osquery_schema_versions
* download section

There was any reason to not publish 5.12.2? We should not use this version? 
I was trying to match (programmatically) the osquery version from binary to an existing json schema (in osquery_schema_versions folder).

Thank you

**Comment by directionless** [comment]
5.12.2 is stable and fine to use. There was an issue with the website automation that effected it, and I didn't manually publish it.

**Comment by lszcs90** [comment]
Thank you.
It will be published this manually or only the next version?

**Comment by directionless** [comment]
I'm not sure. I'd like to think I'll manually publish it. but I haven't done it yet. :(

**Comment by lszcs90** [comment]
Hello,
Can we push on the repo at least the json schema file?
Thanks, 
Szabolcs

**Comment by lszcs90** [comment]
Hello, 
Any update about this issue?
Thank you.

**Comment by directionless** [comment]
Well, it's not the best answer, but osquery 5.13.1 is stable and on the website.
