### ISSUE TITLE
Display summaries of blog posts

### ISSUE THREAD

**Issue by mattjane-okta** [osquery/osquery-site#30]
## Isssue

Currently the page displays the article in full, requiring the user to scroll through an entire post just to see if there are any more to view.  

### Suggestion

Move to displaying a headline + 5-10 lines of the article and perhaps add at ToC to the side to allow people to easily browse the headlines for articles relevant to their needs.

**Comment by clong** [comment]
Strong +1 here. The page is almost unusable in this state in my opinion. There used to be about a dozen different articles linked on the old site.
