### ISSUE TITLE
Create a "Featured Queries & Packs" page

### ISSUE THREAD

**Issue by marpaia** [osquery/osquery-site#40]
This page should showcase the packs from [facebook/osquery](https://github.com/facebook/osquery/tree/master/packs), [palantir/osquery-configuration](https://github.com/palantir/osquery-configuration), etc.

![osqueryio-packs-revised](https://user-images.githubusercontent.com/927168/35772054-b14a6490-08f4-11e8-92cc-b9c0125149d4.png)

**Comment by reedloden** [comment]
Something like https://web.archive.org/web/20151231160821/https://osquery.io/docs/packs/ is desperately needed again.

**Comment by directionless** [comment]
I don't think this is on anyone's plans
