### ISSUE TITLE
Copying commands to install packages shouldn't copy $

### ISSUE THREAD

**Issue by marpaia** [osquery/osquery-site#50]
When copying these commands, it would be awesome if we could omit the `$ ` from what gets highlighted and copied to the clipboard.

<img width="979" alt="screen shot 2018-02-21 at 3 46 52 pm" src="https://user-images.githubusercontent.com/927168/36512268-87141e40-171e-11e8-957b-b173c382f71c.png">

**Comment by ageis** [comment]
Providing a JavaScript copy button for the text inside that element might improve it too.... And at least you're not piping scripts from curl/wget into a shell ;) So many fanatically against that yet it's so common.
