### ISSUE TITLE
Links to tables in schema must specify version

### ISSUE THREAD

**Issue by zwass** [osquery/osquery-site#51]
The osquery docs include various references to table schemas of the form https://osquery.io/schema/#file. These links no longer work. Instead, they would need to be replaced with links of the form https://osquery.io/schema/2.11.2#file. With that, they would quickly become outdated.

Maybe we can make the existing links work? If not, maybe https://osquery.io/schema/current#file?

**Comment by nhpace** [comment]
Updated with PR #72. In addition, submitted https://github.com/facebook/osquery/pull/4451 to manage the doc side changes.

**Comment by nhpace** [comment]
facebook/osquery#4451 has been merged. Once deployed, we should be able to close this.

**Comment by zwass** [comment]
Does #72 fix links like below?

<img width="909" alt="screen shot 2018-06-05 at 5 14 26 pm" src="https://user-images.githubusercontent.com/575602/41009129-ebc28f90-68e3-11e8-875a-5c1e1e10efb6.png">

**Comment by Smjert** [comment]
This seems to be definitely still an issue: https://github.com/osquery/osquery/issues/6367
