### ISSUE TITLE
failed to fetch react-css

### ISSUE THREAD

**Issue by groob** [osquery/osquery-site#6]
![screenshot 2018-01-12 15 46 45](https://user-images.githubusercontent.com/1526945/34894537-dc55d1e8-f7af-11e7-8b32-a09687f9e3b7.png)

notice that there are two GET requests. one of them 404s and one of them redirects. 
<img width="677" alt="screenshot 2018-01-12 15 43 53" src="https://user-images.githubusercontent.com/1526945/34894544-e0f84fd2-f7af-11e7-96c1-ff014db8d14d.png">

**Comment by marpaia** [comment]
Not sure what happened, but this error is no longer showing up in the console.
