### ISSUE TITLE
Star counts incorrect in community projects

### ISSUE THREAD

**Issue by zwass** [osquery/osquery-site#84]
<img width="953" alt="screen shot 2018-06-01 at 2 34 23 pm" src="https://user-images.githubusercontent.com/575602/40864517-07977872-65a9-11e8-899f-ffc262577838.png">
<img width="1033" alt="screen shot 2018-06-01 at 2 34 34 pm" src="https://user-images.githubusercontent.com/575602/40864519-07ad62b8-65a9-11e8-80f9-1292534dd6d2.png">

**Comment by zwass** [comment]
As of a week or two ago these counts were updated dynamically. I wonder if there was some regression?

**Comment by kyleknighted** [comment]
`src/data/featured_projects.json` is where this data is being parsed.

**Comment by nhpace** [comment]
Was looking at this tonight - it appears to be working correctly.

<img width="1578" alt="2018-06-07 20-24-53" src="https://user-images.githubusercontent.com/4217759/41132780-ec39d182-6a90-11e8-9335-89f2a38a67df.png">

**Comment by zwass** [comment]
Does it load some default values and then try to hit the API? Is it possible there was some transient error with the API I was experiencing?

**Comment by nhpace** [comment]
Absolutely possible. In this case, the hard-coded values would be rendered, as they are in your screenshot. We could replace all those hard coded values with an empty value, as the hard coded values are not very valuable.

**Comment by nhpace** [comment]
BTW, this is also true for the description, owner and url. These values are all hard-coded locally and updated based on the GitHub API response. If the request fails, this other information could also, potentially, be stale.

**Comment by marpaia** [comment]
Can we change it to be something ambiguous like question marks or something before the fetch has happened? It's pretty low on the page, so it would probably be a fine opportunity to do something async?

**Comment by nhpace** [comment]
Yes, I have a local change for the star defaults being "--". I will get that in.

**Comment by zwass** [comment]
Generally the loading from Github seems to work. As of now I feel that falling back to the default hardcoded values (which represent the star counts at some time in the past) is a fine solution. We can occasionally update the hardcoded values.
