### ISSUE TITLE
Please add slack.osquery.io cname to point to signup page

### ISSUE THREAD

**Issue by arubdesu** [osquery/osquery-site#85]
Pardon that @terracatta suggested I file this here... currently we're still using the direct herokuapp link on the main osquery repo README for Slack signup. Please add the cname slack.osquery.io to point to https://osquery-slack.herokuapp.com/ so we can update that link. Thanks!

**Comment by marpaia** [comment]
I think @theopolis is the man you need for osquery.io DNS, but I think this is a great idea personally!

**Comment by marpaia** [comment]
This works now! Thanks @theopolis! https://slack.osquery.io
