### ISSUE TITLE
Website "jumps around" when mousing over the schema reference

### ISSUE THREAD

**Issue by muffins** [osquery/osquery-site#93]
See the [osquery issue for reference.](https://github.com/facebook/osquery/issues/4526)

In the schema documentation, when mousing over the list of tables to the left, the scrollbar for the main browser window is hidden, causing the content of the page to "jump around" as it shifts left and right depending on whether the scrollbar is present.

Tested in both current Chrome and Firefox.

**Comment by nhpace** [comment]
This is a duplicate of #43

**Comment by muffins** [comment]
Closing as it’s a duplicate
